### PR TITLE
add p properties files for p deployer

### PR DESCRIPTION
**Pull request by quentinus95**

### CODE REVIEW

**Comment by quentinus95** [comment]
@IGI-111 this PR adds a p-properties file to manage installation with the new p-deployer

**Review by IGI-111 — APPROVED** [review]
Sounds good.

**Comment by IGI-111** [comment]
Do we have a formal spec for the deployer files somewhere or not?

**Comment by quentinus95** [comment]
Nope, I will add one ASAP.

**Comment by quentinus95** [comment]
@IGI-111 you can see the P-Deployer Readme with updated instructions

**Pull request merged**
